// ...existing code...
import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { AuthInterceptor } from '../app/core/interceptors/auth.interceptor';
import { NgModule } from '@angular/core';
 // ...existing code...
 @NgModule({
   // ...existing code...
   providers: [
     // ...existing providers...
     { provide: HTTP_INTERCEPTORS, useClass: AuthInterceptor, multi: true }
   ],
   // ...existing code...
 })
 export class AppModule { }
 // ...existing code...